/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Safal
 */
public class Signup extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Signup.class.getName());

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jTextField12 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        GharSathi_Text = new javax.swing.JTextField();
        System_Text = new javax.swing.JTextField();
        SearchBar_Button = new javax.swing.JButton();
        SearchHouse_Button = new javax.swing.JButton();
        Bookings_Button = new javax.swing.JButton();
        SavedHouse_Button = new javax.swing.JButton();
        Profile_Button = new javax.swing.JButton();
        Dashboard_Button = new javax.swing.JButton();
        Iconlogo_Button = new javax.swing.JButton();
        Username_Text = new javax.swing.JTextField();
        NotificationIcon_Button = new javax.swing.JButton();
        Iconlogo_Button2 = new javax.swing.JButton();
        Info_Panel = new javax.swing.JPanel();
        Info_text = new javax.swing.JTextField();
        Info_text2 = new javax.swing.JTextField();
        Info_text3 = new javax.swing.JLabel();
        Explore_Button = new javax.swing.JButton();
        Conforimed_Panel = new javax.swing.JPanel();
        Conforimned_Text = new javax.swing.JTextField();
        ConforimnedText = new javax.swing.JTextField();
        Conforimned_Icon = new javax.swing.JLabel();
        TotalHouse_Panel = new javax.swing.JPanel();
        TotalHouseNo_Text = new javax.swing.JTextField();
        TotalHouse_Text = new javax.swing.JTextField();
        TotalHouse_Icon = new javax.swing.JLabel();
        MyBookings_Panel = new javax.swing.JPanel();
        MyBookingsNo_Text = new javax.swing.JTextField();
        MyBookings_Text = new javax.swing.JTextField();
        MyBookings_Icon = new javax.swing.JLabel();
        Cancelled_Panel = new javax.swing.JPanel();
        CancelledNo_text = new javax.swing.JTextField();
        Cancelled_text = new javax.swing.JTextField();
        CancelledIcon = new javax.swing.JLabel();
        RecommendedHouse_Text = new javax.swing.JTextField();
        RecommendedHouse_Panel = new javax.swing.JPanel();
        House1Name_Text = new javax.swing.JTextField();
        House3Name_Text = new javax.swing.JTextField();
        House2Name_Text = new javax.swing.JTextField();
        House1Price_Text = new javax.swing.JTextField();
        House2Price_Text = new javax.swing.JTextField();
        House3Price_Text = new javax.swing.JTextField();
        RecommendedHouse1_Img = new javax.swing.JLabel();
        RecommendedHouse2_Img = new javax.swing.JLabel();
        RecommendedHouse3_Img = new javax.swing.JLabel();
        RecommendedHouse3_BUtton = new javax.swing.JButton();
        RecommendedHouse2_BUtton = new javax.swing.JButton();
        RecommendedHouse1_BUtton = new javax.swing.JButton();
        RecentActivity_Panel = new javax.swing.JPanel();
        RecentActitivity_Text = new javax.swing.JTextField();
        Recent1_Text = new javax.swing.JTextField();
        Recent2_Text = new javax.swing.JTextField();
        Recent3_Text = new javax.swing.JTextField();
        ViewAll_Button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6);
        jPanel6.setBounds(310, 160, 80, 40);

        jTextField12.setBackground(new java.awt.Color(243, 243, 243));
        jTextField12.setFont(new java.awt.Font("Segoe UI", 1, 5)); // NOI18N
        jTextField12.setText("Modern Apartment");
        jTextField12.setBorder(null);
        jTextField12.addActionListener(this::jTextField12ActionPerformed);
        jPanel3.add(jTextField12);
        jTextField12.setBounds(20, 40, 50, 10);

        jTextField14.setBackground(new java.awt.Color(243, 243, 243));
        jTextField14.setFont(new java.awt.Font("Segoe UI", 1, 5)); // NOI18N
        jTextField14.setText("Cozy Home");
        jTextField14.setBorder(null);
        jTextField14.addActionListener(this::jTextField14ActionPerformed);
        jPanel3.add(jTextField14);
        jTextField14.setBounds(200, 40, 50, 10);

        jTextField13.setBackground(new java.awt.Color(243, 243, 243));
        jTextField13.setFont(new java.awt.Font("Segoe UI", 1, 5)); // NOI18N
        jTextField13.setText("Luxury Villa");
        jTextField13.setBorder(null);
        jTextField13.addActionListener(this::jTextField13ActionPerformed);
        jPanel3.add(jTextField13);
        jTextField13.setBounds(110, 40, 50, 10);

        jTextField15.setBackground(new java.awt.Color(243, 243, 243));
        jTextField15.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(53, 100, 166));
        jTextField15.setText("Rs,25K/month");
        jTextField15.setBorder(null);
        jTextField15.addActionListener(this::jTextField15ActionPerformed);
        jPanel3.add(jTextField15);
        jTextField15.setBounds(110, 50, 50, 10);

        jTextField16.setBackground(new java.awt.Color(243, 243, 243));
        jTextField16.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jTextField16.setForeground(new java.awt.Color(53, 100, 166));
        jTextField16.setText("Rs,45K/month");
        jTextField16.setBorder(null);
        jTextField16.addActionListener(this::jTextField16ActionPerformed);
        jPanel3.add(jTextField16);
        jTextField16.setBounds(20, 50, 50, 11);

        jTextField18.setBackground(new java.awt.Color(243, 243, 243));
        jTextField18.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jTextField18.setForeground(new java.awt.Color(53, 100, 166));
        jTextField18.setText("Rs,32K/month");
        jTextField18.setBorder(null);
        jTextField18.addActionListener(this::jTextField18ActionPerformed);
        jPanel3.add(jTextField18);
        jTextField18.setBounds(200, 50, 50, 11);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/lux22).jpg"))); // NOI18N
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 10, 60, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/mans).jpg"))); // NOI18N
        jPanel3.add(jLabel7);
        jLabel7.setBounds(110, 0, 60, 60);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/download (22).jpg"))); // NOI18N
        jPanel3.add(jLabel8);
        jLabel8.setBounds(200, 10, 70, 40);

        jButton2.setBackground(new java.awt.Color(243, 243, 243));
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel3.add(jButton2);
        jButton2.setBounds(190, 10, 70, 60);

        jButton5.setBackground(new java.awt.Color(243, 243, 243));
        jButton5.addActionListener(this::jButton5ActionPerformed);
        jPanel3.add(jButton5);
        jButton5.setBounds(100, 10, 70, 60);

        jButton6.setBackground(new java.awt.Color(243, 243, 243));
        jButton6.addActionListener(this::jButton6ActionPerformed);
        jPanel3.add(jButton6);
        jButton6.setBounds(10, 10, 70, 60);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1540, 860));
        getContentPane().setLayout(null);

        GharSathi_Text.setBackground(new java.awt.Color(243, 243, 243));
        GharSathi_Text.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        GharSathi_Text.setText("System");
        GharSathi_Text.setBorder(null);
        GharSathi_Text.addActionListener(this::GharSathi_TextActionPerformed);
        getContentPane().add(GharSathi_Text);
        GharSathi_Text.setBounds(40, 20, 30, 10);

        System_Text.setBackground(new java.awt.Color(243, 243, 243));
        System_Text.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        System_Text.setText("GharSathi");
        System_Text.setBorder(null);
        System_Text.addActionListener(this::System_TextActionPerformed);
        getContentPane().add(System_Text);
        System_Text.setBounds(40, 0, 50, 30);

        SearchBar_Button.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        SearchBar_Button.setText("Search by Location,house name.......");
        SearchBar_Button.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        SearchBar_Button.addActionListener(this::SearchBar_ButtonActionPerformed);
        getContentPane().add(SearchBar_Button);
        SearchBar_Button.setBounds(110, 10, 150, 15);

        SearchHouse_Button.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        SearchHouse_Button.setText("Search Houses");
        SearchHouse_Button.addActionListener(this::SearchHouse_ButtonActionPerformed);
        getContentPane().add(SearchHouse_Button);
        SearchHouse_Button.setBounds(90, 40, 90, 20);

        Bookings_Button.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Bookings_Button.setText("Bookings");
        Bookings_Button.addActionListener(this::Bookings_ButtonActionPerformed);
        getContentPane().add(Bookings_Button);
        Bookings_Button.setBounds(180, 40, 70, 20);

        SavedHouse_Button.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        SavedHouse_Button.setText("Saved Houses");
        SavedHouse_Button.addActionListener(this::SavedHouse_ButtonActionPerformed);
        getContentPane().add(SavedHouse_Button);
        SavedHouse_Button.setBounds(250, 40, 80, 20);

        Profile_Button.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Profile_Button.setText("Profile");
        Profile_Button.addActionListener(this::Profile_ButtonActionPerformed);
        getContentPane().add(Profile_Button);
        Profile_Button.setBounds(330, 40, 60, 20);

        Dashboard_Button.setBackground(new java.awt.Color(15, 75, 155));
        Dashboard_Button.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Dashboard_Button.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard_Button.setText("Dashboard");
        Dashboard_Button.addActionListener(this::Dashboard_ButtonActionPerformed);
        getContentPane().add(Dashboard_Button);
        Dashboard_Button.setBounds(10, 40, 70, 20);

        Iconlogo_Button.setBackground(new java.awt.Color(243, 243, 243));
        Iconlogo_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Vector (1).png"))); // NOI18N
        Iconlogo_Button.setBorder(null);
        Iconlogo_Button.addActionListener(this::Iconlogo_ButtonActionPerformed);
        getContentPane().add(Iconlogo_Button);
        Iconlogo_Button.setBounds(370, 10, 20, 13);

        Username_Text.setBackground(new java.awt.Color(243, 243, 243));
        Username_Text.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Username_Text.setText("Hello, User");
        Username_Text.setBorder(null);
        Username_Text.addActionListener(this::Username_TextActionPerformed);
        getContentPane().add(Username_Text);
        Username_Text.setBounds(320, 10, 40, 20);

        NotificationIcon_Button.setBackground(new java.awt.Color(243, 243, 243));
        NotificationIcon_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/mi_notification.png"))); // NOI18N
        NotificationIcon_Button.setBorder(null);
        getContentPane().add(NotificationIcon_Button);
        NotificationIcon_Button.setBounds(270, 10, 20, 20);

        Iconlogo_Button2.setBackground(new java.awt.Color(243, 243, 243));
        Iconlogo_Button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/iconamoon_profile-circle-fill.png"))); // NOI18N
        Iconlogo_Button2.setBorder(null);
        Iconlogo_Button2.addActionListener(this::Iconlogo_Button2ActionPerformed);
        getContentPane().add(Iconlogo_Button2);
        Iconlogo_Button2.setBounds(300, 10, 20, 20);

        Info_Panel.setBackground(new java.awt.Color(252, 238, 222));
        Info_Panel.setLayout(null);

        Info_text.setBackground(new java.awt.Color(252, 238, 222));
        Info_text.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Info_text.setText("Welcome back , User!");
        Info_text.setBorder(null);
        Info_text.addActionListener(this::Info_textActionPerformed);
        Info_Panel.add(Info_text);
        Info_text.setBounds(10, 10, 160, 20);

        Info_text2.setBackground(new java.awt.Color(252, 238, 222));
        Info_text2.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Info_text2.setText("Find and book your ideal home easily.");
        Info_text2.setBorder(null);
        Info_text2.addActionListener(this::Info_text2ActionPerformed);
        Info_Panel.add(Info_text2);
        Info_text2.setBounds(10, 30, 140, 11);

        Info_text3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/{588B1E74-C79C-48C4-898A-8BBB8F90127D} 1 (1).png"))); // NOI18N
        Info_text3.setText("jLabel2");
        Info_Panel.add(Info_text3);
        Info_text3.setBounds(130, 0, 245, 90);

        Explore_Button.setBackground(new java.awt.Color(15, 75, 155));
        Explore_Button.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Explore_Button.setForeground(new java.awt.Color(255, 255, 255));
        Explore_Button.setText("Explore Houses");
        Info_Panel.add(Explore_Button);
        Explore_Button.setBounds(10, 50, 110, 20);

        getContentPane().add(Info_Panel);
        Info_Panel.setBounds(10, 70, 380, 80);

        Conforimed_Panel.setBackground(new java.awt.Color(255, 255, 255));
        Conforimed_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Conforimed_Panel.setLayout(null);

        Conforimned_Text.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Conforimned_Text.setText("02");
        Conforimned_Text.setBorder(null);
        Conforimned_Text.addActionListener(this::Conforimned_TextActionPerformed);
        Conforimed_Panel.add(Conforimned_Text);
        Conforimned_Text.setBounds(20, 10, 20, 10);

        ConforimnedText.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        ConforimnedText.setText("Confirmed");
        ConforimnedText.setBorder(null);
        ConforimnedText.addActionListener(this::ConforimnedTextActionPerformed);
        Conforimed_Panel.add(ConforimnedText);
        ConforimnedText.setBounds(20, 20, 50, 10);

        Conforimned_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/line-md_confirm-circle-filled.png"))); // NOI18N
        Conforimned_Icon.setText("jLabel1");
        Conforimed_Panel.add(Conforimned_Icon);
        Conforimned_Icon.setBounds(0, 10, 20, 20);

        getContentPane().add(Conforimed_Panel);
        Conforimed_Panel.setBounds(210, 160, 80, 40);

        TotalHouse_Panel.setBackground(new java.awt.Color(255, 255, 255));
        TotalHouse_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TotalHouse_Panel.setLayout(null);

        TotalHouseNo_Text.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TotalHouseNo_Text.setText("24");
        TotalHouseNo_Text.setBorder(null);
        TotalHouseNo_Text.addActionListener(this::TotalHouseNo_TextActionPerformed);
        TotalHouse_Panel.add(TotalHouseNo_Text);
        TotalHouseNo_Text.setBounds(20, 10, 20, 10);

        TotalHouse_Text.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        TotalHouse_Text.setText("Total Houses");
        TotalHouse_Text.setBorder(null);
        TotalHouse_Text.addActionListener(this::TotalHouse_TextActionPerformed);
        TotalHouse_Panel.add(TotalHouse_Text);
        TotalHouse_Text.setBounds(20, 20, 50, 10);

        TotalHouse_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Component.png"))); // NOI18N
        TotalHouse_Icon.setText("jLabel1");
        TotalHouse_Panel.add(TotalHouse_Icon);
        TotalHouse_Icon.setBounds(0, 10, 20, 20);

        getContentPane().add(TotalHouse_Panel);
        TotalHouse_Panel.setBounds(10, 160, 80, 40);

        MyBookings_Panel.setBackground(new java.awt.Color(255, 255, 255));
        MyBookings_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MyBookings_Panel.setLayout(null);

        MyBookingsNo_Text.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MyBookingsNo_Text.setText("08  ");
        MyBookingsNo_Text.setBorder(null);
        MyBookingsNo_Text.addActionListener(this::MyBookingsNo_TextActionPerformed);
        MyBookings_Panel.add(MyBookingsNo_Text);
        MyBookingsNo_Text.setBounds(30, 10, 20, 10);

        MyBookings_Text.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        MyBookings_Text.setText("My Bookings");
        MyBookings_Text.setBorder(null);
        MyBookings_Text.addActionListener(this::MyBookings_TextActionPerformed);
        MyBookings_Panel.add(MyBookings_Text);
        MyBookings_Text.setBounds(20, 20, 50, 11);

        MyBookings_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pixel_calender-solid.png"))); // NOI18N
        MyBookings_Icon.setText("jLabel1");
        MyBookings_Panel.add(MyBookings_Icon);
        MyBookings_Icon.setBounds(0, 10, 20, 20);

        getContentPane().add(MyBookings_Panel);
        MyBookings_Panel.setBounds(110, 160, 80, 40);

        Cancelled_Panel.setBackground(new java.awt.Color(255, 255, 255));
        Cancelled_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Cancelled_Panel.setLayout(null);

        CancelledNo_text.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CancelledNo_text.setText("06");
        CancelledNo_text.setBorder(null);
        CancelledNo_text.addActionListener(this::CancelledNo_textActionPerformed);
        Cancelled_Panel.add(CancelledNo_text);
        CancelledNo_text.setBounds(20, 10, 20, 10);

        Cancelled_text.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        Cancelled_text.setText("Cancelled");
        Cancelled_text.setBorder(null);
        Cancelled_text.addActionListener(this::Cancelled_textActionPerformed);
        Cancelled_Panel.add(Cancelled_text);
        Cancelled_text.setBounds(20, 20, 50, 10);

        CancelledIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/material-symbols_cancel.png"))); // NOI18N
        CancelledIcon.setText("jLabel1");
        Cancelled_Panel.add(CancelledIcon);
        CancelledIcon.setBounds(0, 10, 20, 20);

        getContentPane().add(Cancelled_Panel);
        Cancelled_Panel.setBounds(310, 160, 80, 40);

        RecommendedHouse_Text.setBackground(new java.awt.Color(243, 243, 243));
        RecommendedHouse_Text.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        RecommendedHouse_Text.setForeground(new java.awt.Color(53, 100, 166));
        RecommendedHouse_Text.setText("Recommended Houses");
        RecommendedHouse_Text.setBorder(null);
        RecommendedHouse_Text.addActionListener(this::RecommendedHouse_TextActionPerformed);
        getContentPane().add(RecommendedHouse_Text);
        RecommendedHouse_Text.setBounds(10, 210, 90, 11);

        RecommendedHouse_Panel.setBackground(new java.awt.Color(255, 255, 255));
        RecommendedHouse_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        RecommendedHouse_Panel.setLayout(null);

        House1Name_Text.setBackground(new java.awt.Color(243, 243, 243));
        House1Name_Text.setFont(new java.awt.Font("Segoe UI", 1, 5)); // NOI18N
        House1Name_Text.setText("Modern Apartment");
        House1Name_Text.setBorder(null);
        House1Name_Text.addActionListener(this::House1Name_TextActionPerformed);
        RecommendedHouse_Panel.add(House1Name_Text);
        House1Name_Text.setBounds(20, 40, 50, 10);

        House3Name_Text.setBackground(new java.awt.Color(243, 243, 243));
        House3Name_Text.setFont(new java.awt.Font("Segoe UI", 1, 5)); // NOI18N
        House3Name_Text.setText("Cozy Home");
        House3Name_Text.setBorder(null);
        House3Name_Text.addActionListener(this::House3Name_TextActionPerformed);
        RecommendedHouse_Panel.add(House3Name_Text);
        House3Name_Text.setBounds(200, 40, 50, 10);

        House2Name_Text.setBackground(new java.awt.Color(243, 243, 243));
        House2Name_Text.setFont(new java.awt.Font("Segoe UI", 1, 5)); // NOI18N
        House2Name_Text.setText("Luxury Villa");
        House2Name_Text.setBorder(null);
        House2Name_Text.addActionListener(this::House2Name_TextActionPerformed);
        RecommendedHouse_Panel.add(House2Name_Text);
        House2Name_Text.setBounds(110, 40, 50, 10);

        House1Price_Text.setBackground(new java.awt.Color(243, 243, 243));
        House1Price_Text.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        House1Price_Text.setForeground(new java.awt.Color(53, 100, 166));
        House1Price_Text.setText("Rs,45K/month");
        House1Price_Text.setBorder(null);
        House1Price_Text.addActionListener(this::House1Price_TextActionPerformed);
        RecommendedHouse_Panel.add(House1Price_Text);
        House1Price_Text.setBounds(20, 51, 60, 10);

        House2Price_Text.setBackground(new java.awt.Color(243, 243, 243));
        House2Price_Text.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        House2Price_Text.setForeground(new java.awt.Color(53, 100, 166));
        House2Price_Text.setText("Rs,25K/month");
        House2Price_Text.setBorder(null);
        House2Price_Text.addActionListener(this::House2Price_TextActionPerformed);
        RecommendedHouse_Panel.add(House2Price_Text);
        House2Price_Text.setBounds(110, 50, 50, 10);

        House3Price_Text.setBackground(new java.awt.Color(243, 243, 243));
        House3Price_Text.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        House3Price_Text.setForeground(new java.awt.Color(53, 100, 166));
        House3Price_Text.setText("Rs,32K/month");
        House3Price_Text.setBorder(null);
        House3Price_Text.addActionListener(this::House3Price_TextActionPerformed);
        RecommendedHouse_Panel.add(House3Price_Text);
        House3Price_Text.setBounds(200, 50, 50, 11);

        RecommendedHouse1_Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/lux22).jpg"))); // NOI18N
        RecommendedHouse_Panel.add(RecommendedHouse1_Img);
        RecommendedHouse1_Img.setBounds(20, 10, 60, 40);

        RecommendedHouse2_Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/mans).jpg"))); // NOI18N
        RecommendedHouse_Panel.add(RecommendedHouse2_Img);
        RecommendedHouse2_Img.setBounds(110, 0, 60, 60);

        RecommendedHouse3_Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/download (22).jpg"))); // NOI18N
        RecommendedHouse_Panel.add(RecommendedHouse3_Img);
        RecommendedHouse3_Img.setBounds(200, 10, 70, 40);

        RecommendedHouse3_BUtton.setBackground(new java.awt.Color(243, 243, 243));
        RecommendedHouse3_BUtton.addActionListener(this::RecommendedHouse3_BUttonActionPerformed);
        RecommendedHouse_Panel.add(RecommendedHouse3_BUtton);
        RecommendedHouse3_BUtton.setBounds(190, 10, 70, 60);

        RecommendedHouse2_BUtton.setBackground(new java.awt.Color(243, 243, 243));
        RecommendedHouse2_BUtton.addActionListener(this::RecommendedHouse2_BUttonActionPerformed);
        RecommendedHouse_Panel.add(RecommendedHouse2_BUtton);
        RecommendedHouse2_BUtton.setBounds(100, 10, 70, 60);

        RecommendedHouse1_BUtton.setBackground(new java.awt.Color(243, 243, 243));
        RecommendedHouse1_BUtton.addActionListener(this::RecommendedHouse1_BUttonActionPerformed);
        RecommendedHouse_Panel.add(RecommendedHouse1_BUtton);
        RecommendedHouse1_BUtton.setBounds(10, 10, 70, 60);

        getContentPane().add(RecommendedHouse_Panel);
        RecommendedHouse_Panel.setBounds(10, 220, 270, 80);

        RecentActivity_Panel.setBackground(new java.awt.Color(255, 255, 255));
        RecentActivity_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        RecentActivity_Panel.setLayout(null);

        RecentActitivity_Text.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        RecentActitivity_Text.setForeground(new java.awt.Color(53, 100, 166));
        RecentActitivity_Text.setText("Recent Activity");
        RecentActitivity_Text.addActionListener(this::RecentActitivity_TextActionPerformed);
        RecentActivity_Panel.add(RecentActitivity_Text);
        RecentActitivity_Text.setBounds(0, 0, 110, 20);

        Recent1_Text.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Recent1_Text.setText("Rented Villa        2026/1/8");
        Recent1_Text.addActionListener(this::Recent1_TextActionPerformed);
        RecentActivity_Panel.add(Recent1_Text);
        Recent1_Text.setBounds(0, 20, 110, 22);

        Recent2_Text.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Recent2_Text.setText("3BHK Flat           2026/2/4");
        Recent2_Text.addActionListener(this::Recent2_TextActionPerformed);
        RecentActivity_Panel.add(Recent2_Text);
        Recent2_Text.setBounds(0, 40, 110, 17);

        Recent3_Text.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Recent3_Text.setText("CozyHome        2026/1/10");
        RecentActivity_Panel.add(Recent3_Text);
        Recent3_Text.setBounds(0, 60, 110, 17);

        getContentPane().add(RecentActivity_Panel);
        RecentActivity_Panel.setBounds(290, 210, 110, 80);

        ViewAll_Button.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        ViewAll_Button.setForeground(new java.awt.Color(53, 100, 166));
        ViewAll_Button.setText("View All");
        getContentPane().add(ViewAll_Button);
        ViewAll_Button.setBounds(210, 208, 70, 10);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1536, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 864, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 370, 1536, 864);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Info_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Info_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Info_textActionPerformed

    private void SearchBar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBar_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBar_ButtonActionPerformed

    private void SearchHouse_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchHouse_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchHouse_ButtonActionPerformed

    private void Profile_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Profile_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Profile_ButtonActionPerformed

    private void Dashboard_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dashboard_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dashboard_ButtonActionPerformed

    private void Info_text2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Info_text2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Info_text2ActionPerformed

    private void Conforimned_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Conforimned_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Conforimned_TextActionPerformed

    private void ConforimnedTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConforimnedTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConforimnedTextActionPerformed

    private void TotalHouseNo_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalHouseNo_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalHouseNo_TextActionPerformed

    private void TotalHouse_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalHouse_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalHouse_TextActionPerformed

    private void MyBookingsNo_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyBookingsNo_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MyBookingsNo_TextActionPerformed

    private void MyBookings_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyBookings_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MyBookings_TextActionPerformed

    private void CancelledNo_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelledNo_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelledNo_textActionPerformed

    private void Cancelled_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelled_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cancelled_textActionPerformed

    private void House1Name_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_House1Name_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_House1Name_TextActionPerformed

    private void House3Name_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_House3Name_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_House3Name_TextActionPerformed

    private void House2Name_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_House2Name_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_House2Name_TextActionPerformed

    private void House2Price_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_House2Price_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_House2Price_TextActionPerformed

    private void House1Price_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_House1Price_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_House1Price_TextActionPerformed

    private void House3Price_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_House3Price_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_House3Price_TextActionPerformed

    private void RecommendedHouse3_BUttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecommendedHouse3_BUttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecommendedHouse3_BUttonActionPerformed

    private void RecommendedHouse2_BUttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecommendedHouse2_BUttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecommendedHouse2_BUttonActionPerformed

    private void RecommendedHouse1_BUttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecommendedHouse1_BUttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecommendedHouse1_BUttonActionPerformed

    private void RecentActitivity_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecentActitivity_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecentActitivity_TextActionPerformed

    private void Recent1_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Recent1_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Recent1_TextActionPerformed

    private void RecommendedHouse_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecommendedHouse_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecommendedHouse_TextActionPerformed

    private void Recent2_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Recent2_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Recent2_TextActionPerformed

    private void Bookings_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bookings_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bookings_ButtonActionPerformed

    private void SavedHouse_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavedHouse_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SavedHouse_ButtonActionPerformed

    private void Username_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_TextActionPerformed

    private void Iconlogo_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iconlogo_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Iconlogo_ButtonActionPerformed

    private void Iconlogo_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iconlogo_Button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Iconlogo_Button2ActionPerformed

    private void GharSathi_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GharSathi_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GharSathi_TextActionPerformed

    private void System_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_System_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_System_TextActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Signup().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bookings_Button;
    private javax.swing.JLabel CancelledIcon;
    private javax.swing.JTextField CancelledNo_text;
    private javax.swing.JPanel Cancelled_Panel;
    private javax.swing.JTextField Cancelled_text;
    private javax.swing.JPanel Conforimed_Panel;
    private javax.swing.JTextField ConforimnedText;
    private javax.swing.JLabel Conforimned_Icon;
    private javax.swing.JTextField Conforimned_Text;
    private javax.swing.JButton Dashboard_Button;
    private javax.swing.JButton Explore_Button;
    private javax.swing.JTextField GharSathi_Text;
    private javax.swing.JTextField House1Name_Text;
    private javax.swing.JTextField House1Price_Text;
    private javax.swing.JTextField House2Name_Text;
    private javax.swing.JTextField House2Price_Text;
    private javax.swing.JTextField House3Name_Text;
    private javax.swing.JTextField House3Price_Text;
    private javax.swing.JButton Iconlogo_Button;
    private javax.swing.JButton Iconlogo_Button2;
    private javax.swing.JPanel Info_Panel;
    private javax.swing.JTextField Info_text;
    private javax.swing.JTextField Info_text2;
    private javax.swing.JLabel Info_text3;
    private javax.swing.JTextField MyBookingsNo_Text;
    private javax.swing.JLabel MyBookings_Icon;
    private javax.swing.JPanel MyBookings_Panel;
    private javax.swing.JTextField MyBookings_Text;
    private javax.swing.JButton NotificationIcon_Button;
    private javax.swing.JButton Profile_Button;
    private javax.swing.JTextField Recent1_Text;
    private javax.swing.JTextField Recent2_Text;
    private javax.swing.JTextField Recent3_Text;
    private javax.swing.JTextField RecentActitivity_Text;
    private javax.swing.JPanel RecentActivity_Panel;
    private javax.swing.JButton RecommendedHouse1_BUtton;
    private javax.swing.JLabel RecommendedHouse1_Img;
    private javax.swing.JButton RecommendedHouse2_BUtton;
    private javax.swing.JLabel RecommendedHouse2_Img;
    private javax.swing.JButton RecommendedHouse3_BUtton;
    private javax.swing.JLabel RecommendedHouse3_Img;
    private javax.swing.JPanel RecommendedHouse_Panel;
    private javax.swing.JTextField RecommendedHouse_Text;
    private javax.swing.JButton SavedHouse_Button;
    private javax.swing.JButton SearchBar_Button;
    private javax.swing.JButton SearchHouse_Button;
    private javax.swing.JTextField System_Text;
    private javax.swing.JTextField TotalHouseNo_Text;
    private javax.swing.JLabel TotalHouse_Icon;
    private javax.swing.JPanel TotalHouse_Panel;
    private javax.swing.JTextField TotalHouse_Text;
    private javax.swing.JTextField Username_Text;
    private javax.swing.JButton ViewAll_Button;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField18;
    // End of variables declaration//GEN-END:variables
}
